/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.jcchikikomori.samples

class App {
    String getGreeting() {
        return '\nHello World! Buy my book!\n'
    }

    static void main(String[] args) {
        println new App().greeting
        println new GenerateXML().output
        // println System.getenv('willie')

        new ReadXML().assertion()
    }
}
